### ISSUE TITLE
hologram subprocess completes async with grunt task

### ISSUE THREAD

**Issue by akdetrick** [jchild3rs/grunt-hologram#8]
https://github.com/jchild3rs/grunt-hologram/blob/master/tasks/hologram.js#L45

It looks like there's no guarantee that the hologram task has actually completed when grunt-hologram completes. 

With larger sets of files for hologram to parse, it's likely that the node process won't complete before grunt begins the next task, making it difficult to use subsequent grunt tasks to manipulate hologram output.

cc @mattkime

**Comment by mattkime** [comment]
looks like there's already a pull request for this - https://github.com/jchild3rs/grunt-hologram/pull/6

**Comment by jchild3rs** [comment]
Merged in and published at version 0.0.7
